# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(blank=True, null=True)),
                ('fgdzc', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=50)),
                ('fdate', models.DateTimeField(blank=True, null=True)),
                ('fuser', models.CharField(blank=True, max_length=50, null=True)),
                ('fdep', models.CharField(max_length=50)),
                ('fip', models.GenericIPAddressField(blank=True, null=True)),
                ('fdate_rz', models.DateField()),
                ('fdate_bf', models.DateField(blank=True, null=True)),
                ('smark', models.BooleanField(default=False)),
                ('fstore', models.CharField(blank=True, max_length=50, null=True)),
                ('fuserold', models.CharField(blank=True, max_length=50, null=True)),
                ('f1', models.CharField(blank=True, max_length=30, null=True)),
                ('f2', models.CharField(blank=True, max_length=30, null=True)),
                ('fdate_ys', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='assets',
            name='fstate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='display.State'),
        ),
    ]
